[package]
name = "docthis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0"
tokio = { version = "1.36.0", features = ["full"] }
analyzer = { path = "../../analyzer" }
lsp-client-rs = { path = "../../../lsp-rs" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
serde_json = "1.0"
